// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"

void BuzzerOFF(lv_event_t * e)
{
	// Your code here
}

void BuzzerON(lv_event_t * e)
{
	// Your code here
}

void CoolingON(lv_event_t * e)
{
	// Your code here
}

void CoolingOFF(lv_event_t * e)
{
	// Your code here
}

void HeatingON(lv_event_t * e)
{
	// Your code here
}

void HeatingOFF(lv_event_t * e)
{
	// Your code here
}

void SaveConfig(lv_event_t * e)
{
	// Your code here
}

void KpUpdate(lv_event_t * e)
{
	// Your code here
}

void KiUpdate(lv_event_t * e)
{
	// Your code here
}

void KdUpdate(lv_event_t * e)
{
	// Your code here
}

void KPDown(lv_event_t * e)
{
	// Your code here
}

void KPUp(lv_event_t * e)
{
	// Your code here
}

void KIDown(lv_event_t * e)
{
	// Your code here
}

void KIUp(lv_event_t * e)
{
	// Your code here
}

void KDDown(lv_event_t * e)
{
	// Your code here
}

void KDUp(lv_event_t * e)
{
	// Your code here
}
