// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void BuzzerOFF(lv_event_t * e);
void BuzzerON(lv_event_t * e);
void CoolingON(lv_event_t * e);
void CoolingOFF(lv_event_t * e);
void HeatingON(lv_event_t * e);
void HeatingOFF(lv_event_t * e);
void SaveConfig(lv_event_t * e);
void KpUpdate(lv_event_t * e);
void KiUpdate(lv_event_t * e);
void KdUpdate(lv_event_t * e);
void KPDown(lv_event_t * e);
void KPUp(lv_event_t * e);
void KIDown(lv_event_t * e);
void KIUp(lv_event_t * e);
void KDDown(lv_event_t * e);
void KDUp(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
