// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI

#include "../ui.h"

lv_obj_t * ui_HeaterTempSetScreen = NULL;
lv_obj_t * ui_HeaterKeyboard = NULL;
lv_obj_t * ui_Confirm = NULL;
lv_obj_t * ui_Delete = NULL;
lv_obj_t * ui_Num0 = NULL;
lv_obj_t * ui_NumPanel = NULL;
lv_obj_t * ui_Num1 = NULL;
lv_obj_t * ui_Num2 = NULL;
lv_obj_t * ui_Num3 = NULL;
lv_obj_t * ui_Num4 = NULL;
lv_obj_t * ui_Num5 = NULL;
lv_obj_t * ui_Num6 = NULL;
lv_obj_t * ui_Num7 = NULL;
lv_obj_t * ui_Num8 = NULL;
lv_obj_t * ui_Num9 = NULL;
lv_obj_t * ui_HeaterTempSetDock = NULL;
lv_obj_t * ui_TextHeaterTempSetting = NULL;
lv_obj_t * ui_HeaterTempSetting = NULL;
lv_obj_t * ui_HeaterSetTemp = NULL;
lv_obj_t * ui_TextHeaterCurrentTemp = NULL;
lv_obj_t * ui_HeaterCurrentTemp = NULL;
lv_obj_t * ui_RSS = NULL;
lv_obj_t * ui_TextRSS = NULL;
lv_obj_t * ui_RTS = NULL;
lv_obj_t * ui_TextRTS = NULL;
lv_obj_t * ui_USER = NULL;
lv_obj_t * ui_TextUSER = NULL;
lv_obj_t * ui_HeaterTempSetBack = NULL;
// event funtions

// build funtions

void ui_HeaterTempSetScreen_screen_init(void)
{
    ui_HeaterTempSetScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HeaterTempSetScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HeaterTempSetScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeaterTempSetScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaterKeyboard = lv_obj_create(ui_HeaterTempSetScreen);
    lv_obj_remove_style_all(ui_HeaterKeyboard);
    lv_obj_set_width(ui_HeaterKeyboard, 282);
    lv_obj_set_height(ui_HeaterKeyboard, 137);
    lv_obj_set_x(ui_HeaterKeyboard, 36);
    lv_obj_set_y(ui_HeaterKeyboard, 100);
    lv_obj_clear_flag(ui_HeaterKeyboard, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HeaterKeyboard, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_HeaterKeyboard, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Container);
    ui_object_set_themeable_style_property(ui_HeaterKeyboard, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Container);

    ui_Confirm = lv_btn_create(ui_HeaterKeyboard);
    lv_obj_set_width(ui_Confirm, 77);
    lv_obj_set_height(ui_Confirm, 32);
    lv_obj_set_x(ui_Confirm, -15);
    lv_obj_set_y(ui_Confirm, 12);
    lv_obj_set_align(ui_Confirm, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Confirm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Confirm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Confirm, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Confirm, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonPressed);
    ui_object_set_themeable_style_property(ui_Confirm, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonPressed);
    lv_obj_set_style_bg_img_src(ui_Confirm, &ui_img_938671949, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Confirm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Confirm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Delete = lv_btn_create(ui_HeaterKeyboard);
    lv_obj_set_width(ui_Delete, 76);
    lv_obj_set_height(ui_Delete, 32);
    lv_obj_set_x(ui_Delete, -15);
    lv_obj_set_y(ui_Delete, 52);
    lv_obj_set_align(ui_Delete, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Delete, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Delete, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Delete, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Delete, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Delete, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Delete, &ui_img_13634893, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Delete, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Delete, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Num0 = lv_btn_create(ui_HeaterKeyboard);
    lv_obj_set_width(ui_Num0, 76);
    lv_obj_set_height(ui_Num0, 32);
    lv_obj_set_x(ui_Num0, -15);
    lv_obj_set_y(ui_Num0, 92);
    lv_obj_set_align(ui_Num0, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Num0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Num0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Num0, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Num0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Num0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_bg_img_src(ui_Num0, &ui_img_num0_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Num0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Num0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Num0, &ui_img_num0_png, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(ui_Num0, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_ButtonPressed);
    ui_object_set_themeable_style_property(ui_Num0, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ButtonPressed);

    ui_NumPanel = lv_obj_create(ui_HeaterKeyboard);
    lv_obj_set_width(ui_NumPanel, 190);
    lv_obj_set_height(ui_NumPanel, 136);
    lv_obj_set_flex_flow(ui_NumPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_NumPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NumPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NumPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NumPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NumPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NumPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Num1 = lv_btn_create(ui_NumPanel);
    lv_obj_set_width(ui_Num1, 48);
    lv_obj_set_height(ui_Num1, 32);
    lv_obj_set_x(ui_Num1, -20);
    lv_obj_set_y(ui_Num1, -6);
    lv_obj_set_align(ui_Num1, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_Num1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Num1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Num1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Num1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Num1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Num1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Num1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_bg_img_src(ui_Num1, &ui_img_num1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Num1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Num1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Num1, &ui_img_num1_png, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(ui_Num1, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_ButtonPressed);
    ui_object_set_themeable_style_property(ui_Num1, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ButtonPressed);

    ui_Num2 = lv_btn_create(ui_NumPanel);
    lv_obj_set_width(ui_Num2, 48);
    lv_obj_set_height(ui_Num2, 32);
    lv_obj_set_x(ui_Num2, -216);
    lv_obj_set_y(ui_Num2, 7);
    lv_obj_set_align(ui_Num2, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_Num2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Num2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Num2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Num2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Num2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Num2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Num2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_bg_img_src(ui_Num2, &ui_img_num2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Num2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Num2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Num2, &ui_img_num2_png, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(ui_Num2, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_ButtonPressed);
    ui_object_set_themeable_style_property(ui_Num2, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ButtonPressed);

    ui_Num3 = lv_btn_create(ui_NumPanel);
    lv_obj_set_width(ui_Num3, 48);
    lv_obj_set_height(ui_Num3, 32);
    lv_obj_set_x(ui_Num3, -151);
    lv_obj_set_y(ui_Num3, 2);
    lv_obj_set_align(ui_Num3, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_Num3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Num3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Num3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Num3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Num3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Num3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Num3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_bg_img_src(ui_Num3, &ui_img_num3_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Num3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Num3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Num3, &ui_img_num3_png, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(ui_Num3, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_ButtonPressed);
    ui_object_set_themeable_style_property(ui_Num3, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ButtonPressed);

    ui_Num4 = lv_btn_create(ui_NumPanel);
    lv_obj_set_width(ui_Num4, 48);
    lv_obj_set_height(ui_Num4, 32);
    lv_obj_set_x(ui_Num4, -89);
    lv_obj_set_y(ui_Num4, 7);
    lv_obj_set_align(ui_Num4, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_Num4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Num4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Num4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Num4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Num4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Num4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Num4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_bg_img_src(ui_Num4, &ui_img_num4_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Num4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Num4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Num4, &ui_img_num4_png, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(ui_Num4, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_ButtonPressed);
    ui_object_set_themeable_style_property(ui_Num4, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ButtonPressed);

    ui_Num5 = lv_btn_create(ui_NumPanel);
    lv_obj_set_width(ui_Num5, 48);
    lv_obj_set_height(ui_Num5, 32);
    lv_obj_set_x(ui_Num5, -212);
    lv_obj_set_y(ui_Num5, 53);
    lv_obj_set_align(ui_Num5, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Num5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Num5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Num5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Num5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Num5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_bg_img_src(ui_Num5, &ui_img_num5_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Num5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Num5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Num5, &ui_img_num5_png, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(ui_Num5, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_ButtonPressed);
    ui_object_set_themeable_style_property(ui_Num5, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ButtonPressed);

    ui_Num6 = lv_btn_create(ui_NumPanel);
    lv_obj_set_width(ui_Num6, 48);
    lv_obj_set_height(ui_Num6, 32);
    lv_obj_set_x(ui_Num6, -153);
    lv_obj_set_y(ui_Num6, 52);
    lv_obj_set_align(ui_Num6, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Num6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Num6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Num6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Num6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Num6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_bg_img_src(ui_Num6, &ui_img_num6_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Num6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Num6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Num6, &ui_img_num6_png, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(ui_Num6, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_ButtonPressed);
    ui_object_set_themeable_style_property(ui_Num6, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ButtonPressed);

    ui_Num7 = lv_btn_create(ui_NumPanel);
    lv_obj_set_width(ui_Num7, 48);
    lv_obj_set_height(ui_Num7, 32);
    lv_obj_set_x(ui_Num7, -90);
    lv_obj_set_y(ui_Num7, 54);
    lv_obj_set_align(ui_Num7, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Num7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Num7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Num7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Num7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Num7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_bg_img_src(ui_Num7, &ui_img_num7_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Num7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Num7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Num7, &ui_img_num7_png, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(ui_Num7, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_ButtonPressed);
    ui_object_set_themeable_style_property(ui_Num7, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ButtonPressed);

    ui_Num8 = lv_btn_create(ui_NumPanel);
    lv_obj_set_width(ui_Num8, 48);
    lv_obj_set_height(ui_Num8, 32);
    lv_obj_set_x(ui_Num8, -212);
    lv_obj_set_y(ui_Num8, 97);
    lv_obj_set_align(ui_Num8, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Num8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Num8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Num8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Num8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Num8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_bg_img_src(ui_Num8, &ui_img_num8_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Num8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Num8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Num8, &ui_img_num8_png, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(ui_Num8, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_ButtonPressed);
    ui_object_set_themeable_style_property(ui_Num8, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ButtonPressed);

    ui_Num9 = lv_btn_create(ui_NumPanel);
    lv_obj_set_width(ui_Num9, 48);
    lv_obj_set_height(ui_Num9, 32);
    lv_obj_set_x(ui_Num9, -154);
    lv_obj_set_y(ui_Num9, 99);
    lv_obj_set_align(ui_Num9, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Num9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Num9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Num9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Num9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Num9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_bg_img_src(ui_Num9, &ui_img_num9_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Num9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Num9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Num9, &ui_img_num9_png, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(ui_Num9, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_ButtonPressed);
    ui_object_set_themeable_style_property(ui_Num9, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ButtonPressed);

    ui_HeaterTempSetDock = lv_obj_create(ui_HeaterTempSetScreen);
    lv_obj_remove_style_all(ui_HeaterTempSetDock);
    lv_obj_set_width(ui_HeaterTempSetDock, 316);
    lv_obj_set_height(ui_HeaterTempSetDock, 20);
    lv_obj_set_x(ui_HeaterTempSetDock, 0);
    lv_obj_set_y(ui_HeaterTempSetDock, 2);
    lv_obj_set_align(ui_HeaterTempSetDock, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_HeaterTempSetDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HeaterTempSetDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeaterTempSetDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeaterTempSetDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextHeaterTempSetting = lv_label_create(ui_HeaterTempSetDock);
    lv_obj_set_width(ui_TextHeaterTempSetting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextHeaterTempSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextHeaterTempSetting, 0);
    lv_obj_set_y(ui_TextHeaterTempSetting, -1);
    lv_obj_set_align(ui_TextHeaterTempSetting, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextHeaterTempSetting, "加热台温度设置");
    ui_object_set_themeable_style_property(ui_TextHeaterTempSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextHeaterTempSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextHeaterTempSetting, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaterTempSetting = lv_obj_create(ui_HeaterTempSetScreen);
    lv_obj_remove_style_all(ui_HeaterTempSetting);
    lv_obj_set_width(ui_HeaterTempSetting, 282);
    lv_obj_set_height(ui_HeaterTempSetting, 72);
    lv_obj_set_x(ui_HeaterTempSetting, 36);
    lv_obj_set_y(ui_HeaterTempSetting, 25);
    lv_obj_clear_flag(ui_HeaterTempSetting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HeaterTempSetting, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeaterTempSetting, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeaterTempSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaterSetTemp = lv_label_create(ui_HeaterTempSetting);
    lv_obj_set_width(ui_HeaterSetTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeaterSetTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeaterSetTemp, 6);
    lv_obj_set_y(ui_HeaterSetTemp, -8);
    lv_obj_set_align(ui_HeaterSetTemp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_HeaterSetTemp, "---℃");
    ui_object_set_themeable_style_property(ui_HeaterSetTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_HeaterSetTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_HeaterSetTemp, &ui_font_ASCII48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextHeaterCurrentTemp = lv_label_create(ui_HeaterTempSetting);
    lv_obj_set_width(ui_TextHeaterCurrentTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextHeaterCurrentTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextHeaterCurrentTemp, 8);
    lv_obj_set_y(ui_TextHeaterCurrentTemp, 22);
    lv_obj_set_align(ui_TextHeaterCurrentTemp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TextHeaterCurrentTemp, "当前温度:");
    ui_object_set_themeable_style_property(ui_TextHeaterCurrentTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextHeaterCurrentTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextHeaterCurrentTemp, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaterCurrentTemp = lv_label_create(ui_HeaterTempSetting);
    lv_obj_set_width(ui_HeaterCurrentTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeaterCurrentTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeaterCurrentTemp, 80);
    lv_obj_set_y(ui_HeaterCurrentTemp, 22);
    lv_obj_set_align(ui_HeaterCurrentTemp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_HeaterCurrentTemp, "000℃");
    ui_object_set_themeable_style_property(ui_HeaterCurrentTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_HeaterCurrentTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_HeaterCurrentTemp, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RSS = lv_btn_create(ui_HeaterTempSetting);
    lv_obj_set_width(ui_RSS, 50);
    lv_obj_set_height(ui_RSS, 64);
    lv_obj_set_x(ui_RSS, -110);
    lv_obj_set_y(ui_RSS, 4);
    lv_obj_set_align(ui_RSS, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_RSS, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RSS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RSS, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_RSS, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_RSS, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_shadow_color(ui_RSS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RSS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextRSS = lv_label_create(ui_RSS);
    lv_obj_set_width(ui_TextRSS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextRSS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextRSS, -1);
    lv_obj_set_y(ui_TextRSS, 0);
    lv_obj_set_align(ui_TextRSS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextRSS, "RSS\n曲线");
    lv_obj_set_style_text_align(ui_TextRSS, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextRSS, &ui_font_ASCII24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RTS = lv_btn_create(ui_HeaterTempSetting);
    lv_obj_set_width(ui_RTS, 50);
    lv_obj_set_height(ui_RTS, 64);
    lv_obj_set_x(ui_RTS, -56);
    lv_obj_set_y(ui_RTS, 4);
    lv_obj_set_align(ui_RTS, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_RTS, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RTS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RTS, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_RTS, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_RTS, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_shadow_color(ui_RTS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RTS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextRTS = lv_label_create(ui_RTS);
    lv_obj_set_width(ui_TextRTS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextRTS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextRTS, -1);
    lv_obj_set_y(ui_TextRTS, 0);
    lv_obj_set_align(ui_TextRTS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextRTS, "RTS\n曲线");
    lv_obj_set_style_text_align(ui_TextRTS, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextRTS, &ui_font_ASCII24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_USER = lv_btn_create(ui_HeaterTempSetting);
    lv_obj_set_width(ui_USER, 50);
    lv_obj_set_height(ui_USER, 64);
    lv_obj_set_x(ui_USER, -2);
    lv_obj_set_y(ui_USER, 4);
    lv_obj_set_align(ui_USER, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_USER, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_USER, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_USER, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_USER, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_USER, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_shadow_color(ui_USER, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_USER, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextUSER = lv_label_create(ui_USER);
    lv_obj_set_width(ui_TextUSER, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextUSER, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextUSER, -1);
    lv_obj_set_y(ui_TextUSER, 0);
    lv_obj_set_align(ui_TextUSER, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextUSER, "自定\n曲线");
    lv_obj_set_style_text_align(ui_TextUSER, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextUSER, &ui_font_ASCII24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaterTempSetBack = lv_btn_create(ui_HeaterTempSetScreen);
    lv_obj_set_width(ui_HeaterTempSetBack, 32);
    lv_obj_set_height(ui_HeaterTempSetBack, 212);
    lv_obj_set_x(ui_HeaterTempSetBack, -286);
    lv_obj_set_y(ui_HeaterTempSetBack, 25);
    lv_obj_set_align(ui_HeaterTempSetBack, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_HeaterTempSetBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HeaterTempSetBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HeaterTempSetBack, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeaterTempSetBack, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeaterTempSetBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_HeaterTempSetBack, &ui_img_852573520, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HeaterTempSetBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HeaterTempSetBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Confirm, ui_event_Confirm, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Delete, ui_event_Delete, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Num0, ui_event_Num0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Num1, ui_event_Num1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Num2, ui_event_Num2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Num3, ui_event_Num3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Num4, ui_event_Num4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Num5, ui_event_Num5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Num6, ui_event_Num6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Num7, ui_event_Num7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Num8, ui_event_Num8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Num9, ui_event_Num9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RSS, ui_event_RSS, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RTS, ui_event_RTS, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_USER, ui_event_USER, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HeaterTempSetBack, ui_event_HeaterTempSetBack, LV_EVENT_ALL, NULL);

}

void ui_HeaterTempSetScreen_screen_destroy(void)
{
    if(ui_HeaterTempSetScreen) lv_obj_del(ui_HeaterTempSetScreen);

    // NULL screen variables
    ui_HeaterTempSetScreen = NULL;
    ui_HeaterKeyboard = NULL;
    ui_Confirm = NULL;
    ui_Delete = NULL;
    ui_Num0 = NULL;
    ui_NumPanel = NULL;
    ui_Num1 = NULL;
    ui_Num2 = NULL;
    ui_Num3 = NULL;
    ui_Num4 = NULL;
    ui_Num5 = NULL;
    ui_Num6 = NULL;
    ui_Num7 = NULL;
    ui_Num8 = NULL;
    ui_Num9 = NULL;
    ui_HeaterTempSetDock = NULL;
    ui_TextHeaterTempSetting = NULL;
    ui_HeaterTempSetting = NULL;
    ui_HeaterSetTemp = NULL;
    ui_TextHeaterCurrentTemp = NULL;
    ui_HeaterCurrentTemp = NULL;
    ui_RSS = NULL;
    ui_TextRSS = NULL;
    ui_RTS = NULL;
    ui_TextRTS = NULL;
    ui_USER = NULL;
    ui_TextUSER = NULL;
    ui_HeaterTempSetBack = NULL;

}
