// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI

#ifndef UI_HEATERTEMPSETSCREEN_H
#define UI_HEATERTEMPSETSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HeaterTempSetScreen
extern void ui_HeaterTempSetScreen_screen_init(void);
extern void ui_HeaterTempSetScreen_screen_destroy(void);
extern lv_obj_t * ui_HeaterTempSetScreen;
extern lv_obj_t * ui_HeaterKeyboard;
extern void ui_event_Confirm(lv_event_t * e);
extern lv_obj_t * ui_Confirm;
extern void ui_event_Delete(lv_event_t * e);
extern lv_obj_t * ui_Delete;
extern void ui_event_Num0(lv_event_t * e);
extern lv_obj_t * ui_Num0;
extern lv_obj_t * ui_NumPanel;
extern void ui_event_Num1(lv_event_t * e);
extern lv_obj_t * ui_Num1;
extern void ui_event_Num2(lv_event_t * e);
extern lv_obj_t * ui_Num2;
extern void ui_event_Num3(lv_event_t * e);
extern lv_obj_t * ui_Num3;
extern void ui_event_Num4(lv_event_t * e);
extern lv_obj_t * ui_Num4;
extern void ui_event_Num5(lv_event_t * e);
extern lv_obj_t * ui_Num5;
extern void ui_event_Num6(lv_event_t * e);
extern lv_obj_t * ui_Num6;
extern void ui_event_Num7(lv_event_t * e);
extern lv_obj_t * ui_Num7;
extern void ui_event_Num8(lv_event_t * e);
extern lv_obj_t * ui_Num8;
extern void ui_event_Num9(lv_event_t * e);
extern lv_obj_t * ui_Num9;
extern lv_obj_t * ui_HeaterTempSetDock;
extern lv_obj_t * ui_TextHeaterTempSetting;
extern lv_obj_t * ui_HeaterTempSetting;
extern lv_obj_t * ui_HeaterSetTemp;
extern lv_obj_t * ui_TextHeaterCurrentTemp;
extern lv_obj_t * ui_HeaterCurrentTemp;
extern void ui_event_RSS(lv_event_t * e);
extern lv_obj_t * ui_RSS;
extern lv_obj_t * ui_TextRSS;
extern void ui_event_RTS(lv_event_t * e);
extern lv_obj_t * ui_RTS;
extern lv_obj_t * ui_TextRTS;
extern void ui_event_USER(lv_event_t * e);
extern lv_obj_t * ui_USER;
extern lv_obj_t * ui_TextUSER;
extern void ui_event_HeaterTempSetBack(lv_event_t * e);
extern lv_obj_t * ui_HeaterTempSetBack;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

