// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern void ui_event_Setting(lv_event_t * e);
extern lv_obj_t * ui_Setting;
extern void ui_event_Buzzer(lv_event_t * e);
extern lv_obj_t * ui_Buzzer;
extern void ui_event_CoolingFan(lv_event_t * e);
extern lv_obj_t * ui_CoolingFan;
extern lv_obj_t * ui_TMP102Dock;
extern lv_obj_t * ui_TMP102Temp;
extern lv_obj_t * ui_ImageTMP102Temp;
extern lv_obj_t * ui_SystemStatusDock;
extern lv_obj_t * ui_BuzzerStatus;
extern lv_obj_t * ui_SleepStatus;
extern lv_obj_t * ui_CoolingStatus;
extern lv_obj_t * ui_Heating;
extern lv_obj_t * ui_TextHeating;
extern lv_obj_t * ui_HeatingMode;
extern lv_obj_t * ui_ImageHeating;
extern lv_obj_t * ui_HeaterDock;
extern lv_obj_t * ui_HeaterTempDock;
extern lv_obj_t * ui_BarHeaterDuty;
extern lv_obj_t * ui_HeaterTemp;
extern lv_obj_t * ui_TextHeaterTemp;
extern lv_obj_t * ui_HeaterSettingDock;
extern lv_obj_t * ui_TextHeaterTragetTemp;
extern lv_obj_t * ui_HeaterTargetTemp;
extern void ui_event_HeaterSet(lv_event_t * e);
extern lv_obj_t * ui_HeaterSet;
extern void ui_event_HeaterSwitch(lv_event_t * e);
extern lv_obj_t * ui_HeaterSwitch;
extern lv_obj_t * ui_HeaterChart;
extern lv_obj_t * ui_ClockDock;
extern lv_obj_t * ui_Clock;
extern lv_obj_t * ui_ImageClock;
extern lv_obj_t * ui_SecondDock;
extern lv_obj_t * ui_Second;
extern lv_obj_t * ui_ImageSecond;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

