// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI

#include "../ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_Setting = NULL;
lv_obj_t * ui_Buzzer = NULL;
lv_obj_t * ui_CoolingFan = NULL;
lv_obj_t * ui_TMP102Dock = NULL;
lv_obj_t * ui_TMP102Temp = NULL;
lv_obj_t * ui_ImageTMP102Temp = NULL;
lv_obj_t * ui_SystemStatusDock = NULL;
lv_obj_t * ui_BuzzerStatus = NULL;
lv_obj_t * ui_SleepStatus = NULL;
lv_obj_t * ui_CoolingStatus = NULL;
lv_obj_t * ui_Heating = NULL;
lv_obj_t * ui_TextHeating = NULL;
lv_obj_t * ui_HeatingMode = NULL;
lv_obj_t * ui_ImageHeating = NULL;
lv_obj_t * ui_HeaterDock = NULL;
lv_obj_t * ui_HeaterTempDock = NULL;
lv_obj_t * ui_BarHeaterDuty = NULL;
lv_obj_t * ui_HeaterTemp = NULL;
lv_obj_t * ui_TextHeaterTemp = NULL;
lv_obj_t * ui_HeaterSettingDock = NULL;
lv_obj_t * ui_TextHeaterTragetTemp = NULL;
lv_obj_t * ui_HeaterTargetTemp = NULL;
lv_obj_t * ui_HeaterSet = NULL;
lv_obj_t * ui_HeaterSwitch = NULL;
lv_obj_t * ui_HeaterChart = NULL;
lv_obj_t * ui_ClockDock = NULL;
lv_obj_t * ui_Clock = NULL;
lv_obj_t * ui_ImageClock = NULL;
lv_obj_t * ui_SecondDock = NULL;
lv_obj_t * ui_Second = NULL;
lv_obj_t * ui_ImageSecond = NULL;
// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_MainScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_MainScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);

    ui_Setting = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Setting, 102);
    lv_obj_set_height(ui_Setting, 44);
    lv_obj_set_x(ui_Setting, -2);
    lv_obj_set_y(ui_Setting, -3);
    lv_obj_set_align(ui_Setting, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Setting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Setting, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setting, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Setting, &ui_img_1671917170, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Setting, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Setting, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Setting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Setting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buzzer = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Buzzer, 102);
    lv_obj_set_height(ui_Buzzer, 44);
    lv_obj_set_x(ui_Buzzer, 2);
    lv_obj_set_y(ui_Buzzer, -3);
    lv_obj_set_align(ui_Buzzer, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Buzzer, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buzzer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Buzzer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Buzzer, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buzzer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Buzzer, &ui_img_1699618864, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buzzer, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buzzer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Buzzer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Buzzer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Buzzer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Buzzer, &ui_img_185202102, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_CoolingFan = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_CoolingFan, 102);
    lv_obj_set_height(ui_CoolingFan, 44);
    lv_obj_set_x(ui_CoolingFan, 0);
    lv_obj_set_y(ui_CoolingFan, -3);
    lv_obj_set_align(ui_CoolingFan, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_CoolingFan, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CoolingFan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CoolingFan, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CoolingFan, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CoolingFan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_CoolingFan, &ui_img_2103744591, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CoolingFan, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CoolingFan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CoolingFan, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CoolingFan, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CoolingFan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_CoolingFan, &ui_img_1708415670, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TMP102Dock = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_TMP102Dock);
    lv_obj_set_width(ui_TMP102Dock, 74);
    lv_obj_set_height(ui_TMP102Dock, 20);
    lv_obj_set_x(ui_TMP102Dock, 2);
    lv_obj_set_y(ui_TMP102Dock, 2);
    lv_obj_clear_flag(ui_TMP102Dock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TMP102Dock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TMP102Dock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TMP102Dock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TMP102Dock, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TMP102Dock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TMP102Dock, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TMP102Temp = lv_label_create(ui_TMP102Dock);
    lv_obj_set_width(ui_TMP102Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TMP102Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TMP102Temp, 20);
    lv_obj_set_y(ui_TMP102Temp, 0);
    lv_obj_set_align(ui_TMP102Temp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TMP102Temp, "00.00℃");
    ui_object_set_themeable_style_property(ui_TMP102Temp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TMP102Temp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TMP102Temp, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageTMP102Temp = lv_img_create(ui_TMP102Dock);
    lv_img_set_src(ui_ImageTMP102Temp, &ui_img_740489818);
    lv_obj_set_width(ui_ImageTMP102Temp, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_ImageTMP102Temp, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_ImageTMP102Temp, -5);
    lv_obj_set_y(ui_ImageTMP102Temp, 0);
    lv_obj_set_align(ui_ImageTMP102Temp, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageTMP102Temp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageTMP102Temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageTMP102Temp, 128);

    ui_SystemStatusDock = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_SystemStatusDock);
    lv_obj_set_width(ui_SystemStatusDock, 66);
    lv_obj_set_height(ui_SystemStatusDock, 20);
    lv_obj_set_x(ui_SystemStatusDock, 252);
    lv_obj_set_y(ui_SystemStatusDock, 2);
    lv_obj_clear_flag(ui_SystemStatusDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SystemStatusDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SystemStatusDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SystemStatusDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SystemStatusDock, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SystemStatusDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SystemStatusDock, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BuzzerStatus = lv_img_create(ui_SystemStatusDock);
    lv_img_set_src(ui_BuzzerStatus, &ui_img_1699618864);
    lv_obj_set_width(ui_BuzzerStatus, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_BuzzerStatus, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_BuzzerStatus, -6);
    lv_obj_set_y(ui_BuzzerStatus, 0);
    lv_obj_set_align(ui_BuzzerStatus, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BuzzerStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BuzzerStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BuzzerStatus, 128);

    ui_SleepStatus = lv_img_create(ui_SystemStatusDock);
    lv_img_set_src(ui_SleepStatus, &ui_img_1249241237);
    lv_obj_set_width(ui_SleepStatus, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_SleepStatus, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_SleepStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SleepStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SleepStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SleepStatus, 128);

    ui_CoolingStatus = lv_img_create(ui_SystemStatusDock);
    lv_img_set_src(ui_CoolingStatus, &ui_img_2103744591);
    lv_obj_set_width(ui_CoolingStatus, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_CoolingStatus, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_CoolingStatus, 6);
    lv_obj_set_y(ui_CoolingStatus, 0);
    lv_obj_set_align(ui_CoolingStatus, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_CoolingStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CoolingStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_CoolingStatus, 128);

    ui_Heating = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_Heating);
    lv_obj_set_width(ui_Heating, 316);
    lv_obj_set_height(ui_Heating, 166);
    lv_obj_set_x(ui_Heating, 2);
    lv_obj_set_y(ui_Heating, 24);
    lv_obj_clear_flag(ui_Heating, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Heating, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Heating, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Heating, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Heating, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Heating, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Heating, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextHeating = lv_label_create(ui_Heating);
    lv_obj_set_width(ui_TextHeating, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextHeating, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextHeating, 20);
    lv_obj_set_y(ui_TextHeating, 0);
    lv_label_set_text(ui_TextHeating, "加热台-PTC");
    lv_obj_set_style_text_color(ui_TextHeating, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextHeating, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextHeating, &ui_font_ASCII19, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeatingMode = lv_label_create(ui_Heating);
    lv_obj_set_width(ui_HeatingMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeatingMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeatingMode, -2);
    lv_obj_set_y(ui_HeatingMode, 0);
    lv_obj_set_align(ui_HeatingMode, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_HeatingMode, "恒温模式");
    lv_obj_set_style_text_color(ui_HeatingMode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeatingMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeatingMode, &ui_font_ASCII19, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageHeating = lv_img_create(ui_Heating);
    lv_img_set_src(ui_ImageHeating, &ui_img_1357884022);
    lv_obj_set_width(ui_ImageHeating, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageHeating, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageHeating, -6);
    lv_obj_set_y(ui_ImageHeating, -6);
    lv_obj_add_flag(ui_ImageHeating, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHeating, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageHeating, 190);
    lv_obj_set_style_radius(ui_ImageHeating, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaterDock = lv_obj_create(ui_Heating);
    lv_obj_remove_style_all(ui_HeaterDock);
    lv_obj_set_width(ui_HeaterDock, 316);
    lv_obj_set_height(ui_HeaterDock, 142);
    lv_obj_set_x(ui_HeaterDock, -1);
    lv_obj_set_y(ui_HeaterDock, 20);
    lv_obj_clear_flag(ui_HeaterDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HeaterDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeaterDock, lv_color_hex(0x31526B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeaterDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HeaterDock, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HeaterDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HeaterDock, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaterTempDock = lv_obj_create(ui_HeaterDock);
    lv_obj_remove_style_all(ui_HeaterTempDock);
    lv_obj_set_width(ui_HeaterTempDock, 152);
    lv_obj_set_height(ui_HeaterTempDock, 69);
    lv_obj_set_x(ui_HeaterTempDock, 1);
    lv_obj_set_y(ui_HeaterTempDock, 1);
    lv_obj_clear_flag(ui_HeaterTempDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarHeaterDuty = lv_bar_create(ui_HeaterTempDock);
    lv_obj_set_width(ui_BarHeaterDuty, 152);
    lv_obj_set_height(ui_BarHeaterDuty, 69);
    lv_obj_set_align(ui_BarHeaterDuty, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_radius(ui_BarHeaterDuty, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarHeaterDuty, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarHeaterDuty, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_anim_time(ui_BarHeaterDuty, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarHeaterDuty, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarHeaterDuty, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarHeaterDuty, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BarHeaterDuty, lv_color_hex(0x343131), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BarHeaterDuty, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BarHeaterDuty, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BarHeaterDuty, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_BarHeaterDuty, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_BarHeaterDuty, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_HeaterTemp = lv_label_create(ui_HeaterTempDock);
    lv_obj_set_width(ui_HeaterTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeaterTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeaterTemp, -2);
    lv_obj_set_y(ui_HeaterTemp, -8);
    lv_label_set_text(ui_HeaterTemp, "000");
    ui_object_set_themeable_style_property(ui_HeaterTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_HeaterTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_HeaterTemp, &ui_font_ASCII88, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HeaterTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HeaterTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextHeaterTemp = lv_label_create(ui_HeaterTempDock);
    lv_obj_set_width(ui_TextHeaterTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextHeaterTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextHeaterTemp, 126);
    lv_obj_set_y(ui_TextHeaterTemp, -1);
    lv_label_set_text(ui_TextHeaterTemp, "℃");
    ui_object_set_themeable_style_property(ui_TextHeaterTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextHeaterTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextHeaterTemp, &ui_font_ASCII48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaterSettingDock = lv_obj_create(ui_HeaterDock);
    lv_obj_remove_style_all(ui_HeaterSettingDock);
    lv_obj_set_width(ui_HeaterSettingDock, 152);
    lv_obj_set_height(ui_HeaterSettingDock, 67);
    lv_obj_set_x(ui_HeaterSettingDock, 1);
    lv_obj_set_y(ui_HeaterSettingDock, 72);
    lv_obj_clear_flag(ui_HeaterSettingDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HeaterSettingDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeaterSettingDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeaterSettingDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextHeaterTragetTemp = lv_label_create(ui_HeaterSettingDock);
    lv_obj_set_width(ui_TextHeaterTragetTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextHeaterTragetTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextHeaterTragetTemp, 2);
    lv_obj_set_y(ui_TextHeaterTragetTemp, -44);
    lv_obj_set_align(ui_TextHeaterTragetTemp, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_TextHeaterTragetTemp, "设定温度:");
    ui_object_set_themeable_style_property(ui_TextHeaterTragetTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextHeaterTragetTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextHeaterTragetTemp, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaterTargetTemp = lv_label_create(ui_HeaterSettingDock);
    lv_obj_set_width(ui_HeaterTargetTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeaterTargetTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeaterTargetTemp, -10);
    lv_obj_set_y(ui_HeaterTargetTemp, 1);
    lv_obj_set_align(ui_HeaterTargetTemp, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_HeaterTargetTemp, "000℃");
    lv_obj_add_flag(ui_HeaterTargetTemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    ui_object_set_themeable_style_property(ui_HeaterTargetTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_HeaterTargetTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_HeaterTargetTemp, &ui_font_ASCII32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HeaterTargetTemp, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HeaterTargetTemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HeaterTargetTemp, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HeaterTargetTemp, -6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_HeaterTargetTemp, 5, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_color(ui_HeaterTargetTemp, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_HeaterTargetTemp, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_radius(ui_HeaterTargetTemp, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_HeaterTargetTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_HeaterTargetTemp, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_HeaterTargetTemp, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_HeaterTargetTemp, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_HeaterTargetTemp, 5, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_color(ui_HeaterTargetTemp, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_HeaterTargetTemp, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_HeaterTargetTemp, 1, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_HeaterTargetTemp, 1, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_HeaterSet = lv_btn_create(ui_HeaterSettingDock);
    lv_obj_set_width(ui_HeaterSet, 72);
    lv_obj_set_height(ui_HeaterSet, 36);
    lv_obj_set_x(ui_HeaterSet, -2);
    lv_obj_set_y(ui_HeaterSet, -2);
    lv_obj_set_align(ui_HeaterSet, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_HeaterSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HeaterSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HeaterSet, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeaterSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeaterSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_HeaterSet, &ui_img_155116563, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HeaterSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HeaterSet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaterSwitch = lv_btn_create(ui_HeaterSettingDock);
    lv_obj_set_width(ui_HeaterSwitch, 72);
    lv_obj_set_height(ui_HeaterSwitch, 36);
    lv_obj_set_x(ui_HeaterSwitch, 2);
    lv_obj_set_y(ui_HeaterSwitch, -2);
    lv_obj_set_align(ui_HeaterSwitch, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_HeaterSwitch, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HeaterSwitch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HeaterSwitch, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeaterSwitch, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeaterSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_HeaterSwitch, &ui_img_1347724781, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HeaterSwitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HeaterSwitch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_HeaterSwitch, &ui_img_413634367, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_HeaterChart = lv_chart_create(ui_HeaterDock);
    lv_obj_set_width(ui_HeaterChart, 139);
    lv_obj_set_height(ui_HeaterChart, 138);
    lv_obj_set_x(ui_HeaterChart, 173);
    lv_obj_set_y(ui_HeaterChart, 1);
    lv_chart_set_type(ui_HeaterChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_HeaterChart, 128);
    lv_chart_set_range(ui_HeaterChart, LV_CHART_AXIS_PRIMARY_Y, 0, 400);
    lv_chart_set_range(ui_HeaterChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_HeaterChart, 10, 0);
    lv_chart_set_axis_tick(ui_HeaterChart, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_HeaterChart, LV_CHART_AXIS_PRIMARY_Y, 1, 0, 5, 1, true, 0);
    lv_chart_set_axis_tick(ui_HeaterChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    lv_obj_set_style_radius(ui_HeaterChart, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HeaterChart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_HeaterChart, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_HeaterChart, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_HeaterChart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_HeaterChart, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeaterChart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeaterChart, &ui_font_Chart, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_ClockDock = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_ClockDock);
    lv_obj_set_width(ui_ClockDock, 74);
    lv_obj_set_height(ui_ClockDock, 20);
    lv_obj_set_x(ui_ClockDock, 80);
    lv_obj_set_y(ui_ClockDock, 2);
    lv_obj_clear_flag(ui_ClockDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ClockDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ClockDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClockDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ClockDock, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ClockDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ClockDock, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clock = lv_label_create(ui_ClockDock);
    lv_obj_set_width(ui_Clock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Clock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Clock, 24);
    lv_obj_set_y(ui_Clock, 0);
    lv_obj_set_align(ui_Clock, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Clock, "00:00");
    ui_object_set_themeable_style_property(ui_Clock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_Clock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_Clock, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageClock = lv_img_create(ui_ClockDock);
    lv_img_set_src(ui_ImageClock, &ui_img_295618317);
    lv_obj_set_width(ui_ImageClock, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_ImageClock, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_ImageClock, -5);
    lv_obj_set_y(ui_ImageClock, 0);
    lv_obj_set_align(ui_ImageClock, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageClock, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageClock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageClock, 128);

    ui_SecondDock = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_SecondDock);
    lv_obj_set_width(ui_SecondDock, 74);
    lv_obj_set_height(ui_SecondDock, 20);
    lv_obj_set_x(ui_SecondDock, 158);
    lv_obj_set_y(ui_SecondDock, 2);
    lv_obj_clear_flag(ui_SecondDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SecondDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SecondDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SecondDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SecondDock, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SecondDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SecondDock, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Second = lv_label_create(ui_SecondDock);
    lv_obj_set_width(ui_Second, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Second, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Second, 22);
    lv_obj_set_y(ui_Second, 0);
    lv_obj_set_align(ui_Second, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Second, "00000S");
    ui_object_set_themeable_style_property(ui_Second, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_Second, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_Second, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSecond = lv_img_create(ui_SecondDock);
    lv_img_set_src(ui_ImageSecond, &ui_img_295618317);
    lv_obj_set_width(ui_ImageSecond, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_ImageSecond, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_ImageSecond, -5);
    lv_obj_set_y(ui_ImageSecond, 0);
    lv_obj_set_align(ui_ImageSecond, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageSecond, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSecond, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageSecond, 128);

    lv_obj_add_event_cb(ui_Setting, ui_event_Setting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buzzer, ui_event_Buzzer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CoolingFan, ui_event_CoolingFan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HeaterSet, ui_event_HeaterSet, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HeaterSwitch, ui_event_HeaterSwitch, LV_EVENT_ALL, NULL);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_Setting = NULL;
    ui_Buzzer = NULL;
    ui_CoolingFan = NULL;
    ui_TMP102Dock = NULL;
    ui_TMP102Temp = NULL;
    ui_ImageTMP102Temp = NULL;
    ui_SystemStatusDock = NULL;
    ui_BuzzerStatus = NULL;
    ui_SleepStatus = NULL;
    ui_CoolingStatus = NULL;
    ui_Heating = NULL;
    ui_TextHeating = NULL;
    ui_HeatingMode = NULL;
    ui_ImageHeating = NULL;
    ui_HeaterDock = NULL;
    ui_HeaterTempDock = NULL;
    ui_BarHeaterDuty = NULL;
    ui_HeaterTemp = NULL;
    ui_TextHeaterTemp = NULL;
    ui_HeaterSettingDock = NULL;
    ui_TextHeaterTragetTemp = NULL;
    ui_HeaterTargetTemp = NULL;
    ui_HeaterSet = NULL;
    ui_HeaterSwitch = NULL;
    ui_HeaterChart = NULL;
    ui_ClockDock = NULL;
    ui_Clock = NULL;
    ui_ImageClock = NULL;
    ui_SecondDock = NULL;
    ui_Second = NULL;
    ui_ImageSecond = NULL;

}
