// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI

#include "../ui.h"

lv_obj_t * ui_PIDSettingScreen = NULL;
lv_obj_t * ui_PIDSettingHeader = NULL;
lv_obj_t * ui_TextPIDSettingHeader = NULL;
lv_obj_t * ui_PIDSettingBack = NULL;
lv_obj_t * ui_PIDSettingDock = NULL;
lv_obj_t * ui_TextHeatingPID = NULL;
lv_obj_t * ui_HeaterKP = NULL;
lv_obj_t * ui_TextPIDKP = NULL;
lv_obj_t * ui_HeaterKI = NULL;
lv_obj_t * ui_TextPIDKI = NULL;
lv_obj_t * ui_HeaterKD = NULL;
lv_obj_t * ui_TextPIDKD = NULL;
lv_obj_t * ui_KPDown = NULL;
lv_obj_t * ui_KPUp = NULL;
lv_obj_t * ui_KIDown = NULL;
lv_obj_t * ui_KIUp = NULL;
lv_obj_t * ui_KDDown = NULL;
lv_obj_t * ui_KDUp = NULL;
// event funtions

// build funtions

void ui_PIDSettingScreen_screen_init(void)
{
    ui_PIDSettingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PIDSettingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_PIDSettingScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_PIDSettingScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);

    ui_PIDSettingHeader = lv_obj_create(ui_PIDSettingScreen);
    lv_obj_remove_style_all(ui_PIDSettingHeader);
    lv_obj_set_width(ui_PIDSettingHeader, 316);
    lv_obj_set_height(ui_PIDSettingHeader, 20);
    lv_obj_set_x(ui_PIDSettingHeader, 0);
    lv_obj_set_y(ui_PIDSettingHeader, 2);
    lv_obj_set_align(ui_PIDSettingHeader, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PIDSettingHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PIDSettingHeader, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PIDSettingHeader, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PIDSettingHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextPIDSettingHeader = lv_label_create(ui_PIDSettingHeader);
    lv_obj_set_width(ui_TextPIDSettingHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextPIDSettingHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextPIDSettingHeader, 0);
    lv_obj_set_y(ui_TextPIDSettingHeader, -1);
    lv_obj_set_align(ui_TextPIDSettingHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextPIDSettingHeader, "加热台PID参数设置");
    ui_object_set_themeable_style_property(ui_TextPIDSettingHeader, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextPIDSettingHeader, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextPIDSettingHeader, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PIDSettingBack = lv_btn_create(ui_PIDSettingScreen);
    lv_obj_set_width(ui_PIDSettingBack, 32);
    lv_obj_set_height(ui_PIDSettingBack, 212);
    lv_obj_set_x(ui_PIDSettingBack, -286);
    lv_obj_set_y(ui_PIDSettingBack, 25);
    lv_obj_set_align(ui_PIDSettingBack, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_PIDSettingBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PIDSettingBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PIDSettingBack, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PIDSettingBack, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PIDSettingBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PIDSettingBack, &ui_img_852573520, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PIDSettingBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PIDSettingBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PIDSettingDock = lv_obj_create(ui_PIDSettingScreen);
    lv_obj_set_width(ui_PIDSettingDock, 281);
    lv_obj_set_height(ui_PIDSettingDock, 212);
    lv_obj_set_x(ui_PIDSettingDock, 36);
    lv_obj_set_y(ui_PIDSettingDock, 25);
    lv_obj_clear_flag(ui_PIDSettingDock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_PIDSettingDock, LV_DIR_VER);
    lv_obj_set_style_radius(ui_PIDSettingDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PIDSettingDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PIDSettingDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PIDSettingDock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PIDSettingDock, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PIDSettingDock, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_TextHeatingPID = lv_label_create(ui_PIDSettingDock);
    lv_obj_set_width(ui_TextHeatingPID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextHeatingPID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextHeatingPID, -122);
    lv_obj_set_y(ui_TextHeatingPID, -45);
    lv_obj_set_align(ui_TextHeatingPID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextHeatingPID, "加\n热\n台");
    lv_obj_set_style_text_color(ui_TextHeatingPID, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextHeatingPID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextHeatingPID, &ui_font_ASCII19, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TextHeatingPID, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextHeatingPID, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextHeatingPID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TextHeatingPID, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextHeatingPID, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextHeatingPID, 26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextHeatingPID, 26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaterKP = lv_spinbox_create(ui_PIDSettingDock);
    lv_obj_set_width(ui_HeaterKP, 156);
    lv_obj_set_height(ui_HeaterKP, 37);
    lv_obj_set_x(ui_HeaterKP, 18);
    lv_obj_set_y(ui_HeaterKP, -9);
    lv_obj_set_align(ui_HeaterKP, LV_ALIGN_TOP_MID);
    lv_spinbox_set_digit_format(ui_HeaterKP, 6, 3);
    lv_spinbox_set_range(ui_HeaterKP, 0, 999999);
    lv_spinbox_set_cursor_pos(ui_HeaterKP, 1 - 1);
    lv_obj_set_style_radius(ui_HeaterKP, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_HeaterKP, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_HeaterKP, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_pad_left(ui_HeaterKP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HeaterKP, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HeaterKP, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HeaterKP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_HeaterKP, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_HeaterKP, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_align(ui_HeaterKP, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeaterKP, &ui_font_ASCII24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_HeaterKP, 1, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_TextPIDKP = lv_label_create(ui_HeaterKP);
    lv_obj_set_width(ui_TextPIDKP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextPIDKP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextPIDKP, 2);
    lv_obj_set_y(ui_TextPIDKP, -2);
    lv_obj_set_align(ui_TextPIDKP, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TextPIDKP, "KP");
    lv_obj_set_style_text_color(ui_TextPIDKP, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextPIDKP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextPIDKP, &ui_font_ASCII24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaterKI = lv_spinbox_create(ui_PIDSettingDock);
    lv_obj_set_width(ui_HeaterKI, 156);
    lv_obj_set_height(ui_HeaterKI, 37);
    lv_obj_set_x(ui_HeaterKI, 18);
    lv_obj_set_y(ui_HeaterKI, 30);
    lv_obj_set_align(ui_HeaterKI, LV_ALIGN_TOP_MID);
    lv_spinbox_set_digit_format(ui_HeaterKI, 6, 3);
    lv_spinbox_set_range(ui_HeaterKI, 0, 999999);
    lv_spinbox_set_cursor_pos(ui_HeaterKI, 1 - 1);
    lv_obj_set_style_radius(ui_HeaterKI, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_HeaterKI, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_HeaterKI, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_pad_left(ui_HeaterKI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HeaterKI, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HeaterKI, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HeaterKI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_HeaterKI, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_HeaterKI, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_align(ui_HeaterKI, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeaterKI, &ui_font_ASCII24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_HeaterKI, 1, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_TextPIDKI = lv_label_create(ui_HeaterKI);
    lv_obj_set_width(ui_TextPIDKI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextPIDKI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextPIDKI, 2);
    lv_obj_set_y(ui_TextPIDKI, -2);
    lv_obj_set_align(ui_TextPIDKI, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TextPIDKI, "KI");
    lv_obj_set_style_text_color(ui_TextPIDKI, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextPIDKI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextPIDKI, &ui_font_ASCII24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaterKD = lv_spinbox_create(ui_PIDSettingDock);
    lv_obj_set_width(ui_HeaterKD, 156);
    lv_obj_set_height(ui_HeaterKD, 37);
    lv_obj_set_x(ui_HeaterKD, 18);
    lv_obj_set_y(ui_HeaterKD, 69);
    lv_obj_set_align(ui_HeaterKD, LV_ALIGN_TOP_MID);
    lv_spinbox_set_digit_format(ui_HeaterKD, 6, 3);
    lv_spinbox_set_range(ui_HeaterKD, 0, 999999);
    lv_spinbox_set_cursor_pos(ui_HeaterKD, 1 - 1);
    lv_obj_set_style_radius(ui_HeaterKD, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_HeaterKD, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_HeaterKD, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_pad_left(ui_HeaterKD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HeaterKD, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HeaterKD, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HeaterKD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_HeaterKD, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_HeaterKD, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_align(ui_HeaterKD, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeaterKD, &ui_font_ASCII24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_HeaterKD, 1, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_TextPIDKD = lv_label_create(ui_HeaterKD);
    lv_obj_set_width(ui_TextPIDKD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextPIDKD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextPIDKD, 2);
    lv_obj_set_y(ui_TextPIDKD, -2);
    lv_obj_set_align(ui_TextPIDKD, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TextPIDKD, "KD");
    lv_obj_set_style_text_color(ui_TextPIDKD, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextPIDKD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextPIDKD, &ui_font_ASCII24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KPDown = lv_btn_create(ui_PIDSettingDock);
    lv_obj_set_width(ui_KPDown, 37);
    lv_obj_set_height(ui_KPDown, 37);
    lv_obj_set_x(ui_KPDown, -84);
    lv_obj_set_y(ui_KPDown, -9);
    lv_obj_set_align(ui_KPDown, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_KPDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_KPDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_KPDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KPDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KPDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_KPDown, &ui_img_minus_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_KPDown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_KPDown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_border_width(ui_KPDown, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_KPDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_KPDown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KPUp = lv_btn_create(ui_PIDSettingDock);
    lv_obj_set_width(ui_KPUp, 37);
    lv_obj_set_height(ui_KPUp, 37);
    lv_obj_set_x(ui_KPUp, 118);
    lv_obj_set_y(ui_KPUp, -9);
    lv_obj_set_align(ui_KPUp, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_KPUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_KPUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_KPUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KPUp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KPUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_KPUp, &ui_img_plus_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_KPUp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_KPUp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_border_width(ui_KPUp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_KPUp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_KPUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KIDown = lv_btn_create(ui_PIDSettingDock);
    lv_obj_set_width(ui_KIDown, 37);
    lv_obj_set_height(ui_KIDown, 37);
    lv_obj_set_x(ui_KIDown, -84);
    lv_obj_set_y(ui_KIDown, 30);
    lv_obj_set_align(ui_KIDown, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_KIDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_KIDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_KIDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KIDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KIDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_KIDown, &ui_img_minus_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_KIDown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_KIDown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_border_width(ui_KIDown, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_KIDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_KIDown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KIUp = lv_btn_create(ui_PIDSettingDock);
    lv_obj_set_width(ui_KIUp, 37);
    lv_obj_set_height(ui_KIUp, 37);
    lv_obj_set_x(ui_KIUp, 118);
    lv_obj_set_y(ui_KIUp, 30);
    lv_obj_set_align(ui_KIUp, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_KIUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_KIUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_KIUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KIUp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KIUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_KIUp, &ui_img_plus_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_KIUp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_KIUp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_border_width(ui_KIUp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_KIUp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_KIUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KDDown = lv_btn_create(ui_PIDSettingDock);
    lv_obj_set_width(ui_KDDown, 37);
    lv_obj_set_height(ui_KDDown, 37);
    lv_obj_set_x(ui_KDDown, -84);
    lv_obj_set_y(ui_KDDown, 69);
    lv_obj_set_align(ui_KDDown, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_KDDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_KDDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_KDDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KDDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KDDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_KDDown, &ui_img_minus_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_KDDown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_KDDown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_border_width(ui_KDDown, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_KDDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_KDDown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KDUp = lv_btn_create(ui_PIDSettingDock);
    lv_obj_set_width(ui_KDUp, 37);
    lv_obj_set_height(ui_KDUp, 37);
    lv_obj_set_x(ui_KDUp, 118);
    lv_obj_set_y(ui_KDUp, 69);
    lv_obj_set_align(ui_KDUp, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_KDUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_KDUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_KDUp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KDUp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KDUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_KDUp, &ui_img_plus_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_KDUp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_KDUp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_border_width(ui_KDUp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_KDUp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_KDUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PIDSettingBack, ui_event_PIDSettingBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HeaterKP, ui_event_HeaterKP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HeaterKI, ui_event_HeaterKI, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HeaterKD, ui_event_HeaterKD, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KPDown, ui_event_KPDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KPUp, ui_event_KPUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KIDown, ui_event_KIDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KIUp, ui_event_KIUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KDDown, ui_event_KDDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KDUp, ui_event_KDUp, LV_EVENT_ALL, NULL);

}

void ui_PIDSettingScreen_screen_destroy(void)
{
    if(ui_PIDSettingScreen) lv_obj_del(ui_PIDSettingScreen);

    // NULL screen variables
    ui_PIDSettingScreen = NULL;
    ui_PIDSettingHeader = NULL;
    ui_TextPIDSettingHeader = NULL;
    ui_PIDSettingBack = NULL;
    ui_PIDSettingDock = NULL;
    ui_TextHeatingPID = NULL;
    ui_HeaterKP = NULL;
    ui_TextPIDKP = NULL;
    ui_HeaterKI = NULL;
    ui_TextPIDKI = NULL;
    ui_HeaterKD = NULL;
    ui_TextPIDKD = NULL;
    ui_KPDown = NULL;
    ui_KPUp = NULL;
    ui_KIDown = NULL;
    ui_KIUp = NULL;
    ui_KDDown = NULL;
    ui_KDUp = NULL;

}
