// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI

#ifndef UI_PIDSETTINGSCREEN_H
#define UI_PIDSETTINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PIDSettingScreen
extern void ui_PIDSettingScreen_screen_init(void);
extern void ui_PIDSettingScreen_screen_destroy(void);
extern lv_obj_t * ui_PIDSettingScreen;
extern lv_obj_t * ui_PIDSettingHeader;
extern lv_obj_t * ui_TextPIDSettingHeader;
extern void ui_event_PIDSettingBack(lv_event_t * e);
extern lv_obj_t * ui_PIDSettingBack;
extern lv_obj_t * ui_PIDSettingDock;
extern lv_obj_t * ui_TextHeatingPID;
extern void ui_event_HeaterKP(lv_event_t * e);
extern lv_obj_t * ui_HeaterKP;
extern lv_obj_t * ui_TextPIDKP;
extern void ui_event_HeaterKI(lv_event_t * e);
extern lv_obj_t * ui_HeaterKI;
extern lv_obj_t * ui_TextPIDKI;
extern void ui_event_HeaterKD(lv_event_t * e);
extern lv_obj_t * ui_HeaterKD;
extern lv_obj_t * ui_TextPIDKD;
extern void ui_event_KPDown(lv_event_t * e);
extern lv_obj_t * ui_KPDown;
extern void ui_event_KPUp(lv_event_t * e);
extern lv_obj_t * ui_KPUp;
extern void ui_event_KIDown(lv_event_t * e);
extern lv_obj_t * ui_KIDown;
extern void ui_event_KIUp(lv_event_t * e);
extern lv_obj_t * ui_KIUp;
extern void ui_event_KDDown(lv_event_t * e);
extern lv_obj_t * ui_KDDown;
extern void ui_event_KDUp(lv_event_t * e);
extern lv_obj_t * ui_KDUp;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

