// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI

#ifndef UI_SYSTEMSETTINGSCREEN_H
#define UI_SYSTEMSETTINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SystemSettingScreen
extern void ui_SystemSettingScreen_screen_init(void);
extern void ui_SystemSettingScreen_screen_destroy(void);
extern lv_obj_t * ui_SystemSettingScreen;
extern lv_obj_t * ui_SystemSettingDock;
extern lv_obj_t * ui_TextSystemSetting;
extern void ui_event_SystemSettingBack(lv_event_t * e);
extern lv_obj_t * ui_SystemSettingBack;
extern lv_obj_t * ui_SystemSetting;
extern void ui_event_PIDSetting(lv_event_t * e);
extern lv_obj_t * ui_PIDSetting;
extern lv_obj_t * ui_TextPIDSetting;
extern void ui_event_ReflowSetting(lv_event_t * e);
extern lv_obj_t * ui_ReflowSetting;
extern lv_obj_t * ui_TextReflowSetting;
extern void ui_event_HeaterMaxTemp(lv_event_t * e);
extern lv_obj_t * ui_HeaterMaxTemp;
extern lv_obj_t * ui_TextHeaterMaxTemp;
extern lv_obj_t * ui_NameHeaterMaxTemp;
extern void ui_event_HeatingTime(lv_event_t * e);
extern lv_obj_t * ui_HeatingTime;
extern lv_obj_t * ui_TextHeatingTime;
extern lv_obj_t * ui_NameHeatingTime;
extern void ui_event_SystemBrightness(lv_event_t * e);
extern lv_obj_t * ui_SystemBrightness;
extern lv_obj_t * ui_ImageBrightness;
extern lv_obj_t * ui_TextBrightness;
extern void ui_event_SettingSave(lv_event_t * e);
extern lv_obj_t * ui_SettingSave;
extern lv_obj_t * ui_TextSetting;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

