// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI

#include "../ui.h"

lv_obj_t * ui_SystemSettingScreen = NULL;
lv_obj_t * ui_SystemSettingDock = NULL;
lv_obj_t * ui_TextSystemSetting = NULL;
lv_obj_t * ui_SystemSettingBack = NULL;
lv_obj_t * ui_SystemSetting = NULL;
lv_obj_t * ui_PIDSetting = NULL;
lv_obj_t * ui_TextPIDSetting = NULL;
lv_obj_t * ui_ReflowSetting = NULL;
lv_obj_t * ui_TextReflowSetting = NULL;
lv_obj_t * ui_HeaterMaxTemp = NULL;
lv_obj_t * ui_TextHeaterMaxTemp = NULL;
lv_obj_t * ui_NameHeaterMaxTemp = NULL;
lv_obj_t * ui_HeatingTime = NULL;
lv_obj_t * ui_TextHeatingTime = NULL;
lv_obj_t * ui_NameHeatingTime = NULL;
lv_obj_t * ui_SystemBrightness = NULL;
lv_obj_t * ui_ImageBrightness = NULL;
lv_obj_t * ui_TextBrightness = NULL;
lv_obj_t * ui_SettingSave = NULL;
lv_obj_t * ui_TextSetting = NULL;
// event funtions

// build funtions

void ui_SystemSettingScreen_screen_init(void)
{
    ui_SystemSettingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SystemSettingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SystemSettingScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_SystemSettingScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);

    ui_SystemSettingDock = lv_obj_create(ui_SystemSettingScreen);
    lv_obj_remove_style_all(ui_SystemSettingDock);
    lv_obj_set_width(ui_SystemSettingDock, 316);
    lv_obj_set_height(ui_SystemSettingDock, 20);
    lv_obj_set_x(ui_SystemSettingDock, 0);
    lv_obj_set_y(ui_SystemSettingDock, 2);
    lv_obj_set_align(ui_SystemSettingDock, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_SystemSettingDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SystemSettingDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SystemSettingDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SystemSettingDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextSystemSetting = lv_label_create(ui_SystemSettingDock);
    lv_obj_set_width(ui_TextSystemSetting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextSystemSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextSystemSetting, 0);
    lv_obj_set_y(ui_TextSystemSetting, -1);
    lv_obj_set_align(ui_TextSystemSetting, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextSystemSetting, "系统设置");
    ui_object_set_themeable_style_property(ui_TextSystemSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextSystemSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextSystemSetting, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SystemSettingBack = lv_btn_create(ui_SystemSettingScreen);
    lv_obj_set_width(ui_SystemSettingBack, 32);
    lv_obj_set_height(ui_SystemSettingBack, 212);
    lv_obj_set_x(ui_SystemSettingBack, -286);
    lv_obj_set_y(ui_SystemSettingBack, 25);
    lv_obj_set_align(ui_SystemSettingBack, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_SystemSettingBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SystemSettingBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SystemSettingBack, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SystemSettingBack, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SystemSettingBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SystemSettingBack, &ui_img_852573520, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SystemSettingBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SystemSettingBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SystemSetting = lv_obj_create(ui_SystemSettingScreen);
    lv_obj_set_width(ui_SystemSetting, 281);
    lv_obj_set_height(ui_SystemSetting, 212);
    lv_obj_set_x(ui_SystemSetting, 16);
    lv_obj_set_y(ui_SystemSetting, 25);
    lv_obj_set_align(ui_SystemSetting, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_SystemSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_SystemSetting, LV_DIR_VER);
    lv_obj_set_style_radius(ui_SystemSetting, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SystemSetting, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SystemSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SystemSetting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SystemSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SystemSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SystemSetting, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SystemSetting, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SystemSetting, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_PIDSetting = lv_btn_create(ui_SystemSetting);
    lv_obj_set_width(ui_PIDSetting, 272);
    lv_obj_set_height(ui_PIDSetting, 32);
    lv_obj_set_x(ui_PIDSetting, -8);
    lv_obj_set_y(ui_PIDSetting, -9);
    lv_obj_add_flag(ui_PIDSetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PIDSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PIDSetting, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PIDSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_PIDSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_shadow_color(ui_PIDSetting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PIDSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PIDSetting, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_ButtonPressed);
    ui_object_set_themeable_style_property(ui_PIDSetting, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ButtonPressed);

    ui_TextPIDSetting = lv_label_create(ui_PIDSetting);
    lv_obj_set_width(ui_TextPIDSetting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextPIDSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextPIDSetting, -6);
    lv_obj_set_y(ui_TextPIDSetting, 0);
    lv_obj_set_align(ui_TextPIDSetting, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TextPIDSetting, "加热台 - PID参数设置");
    ui_object_set_themeable_style_property(ui_TextPIDSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextPIDSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextPIDSetting, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReflowSetting = lv_btn_create(ui_SystemSetting);
    lv_obj_set_width(ui_ReflowSetting, 272);
    lv_obj_set_height(ui_ReflowSetting, 32);
    lv_obj_set_x(ui_ReflowSetting, -8);
    lv_obj_set_y(ui_ReflowSetting, 27);
    lv_obj_add_flag(ui_ReflowSetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ReflowSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReflowSetting, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ReflowSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_ReflowSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_shadow_color(ui_ReflowSetting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ReflowSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ReflowSetting, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_ButtonPressed);
    ui_object_set_themeable_style_property(ui_ReflowSetting, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ButtonPressed);

    ui_TextReflowSetting = lv_label_create(ui_ReflowSetting);
    lv_obj_set_width(ui_TextReflowSetting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextReflowSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextReflowSetting, -6);
    lv_obj_set_y(ui_TextReflowSetting, 0);
    lv_obj_set_align(ui_TextReflowSetting, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TextReflowSetting, "加热台 - 自定曲线设置");
    ui_object_set_themeable_style_property(ui_TextReflowSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextReflowSetting, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextReflowSetting, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaterMaxTemp = lv_slider_create(ui_SystemSetting);
    lv_slider_set_range(ui_HeaterMaxTemp, 100, 350);
    lv_slider_set_value(ui_HeaterMaxTemp, 200, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_HeaterMaxTemp) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_HeaterMaxTemp, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_HeaterMaxTemp, 268);
    lv_obj_set_height(ui_HeaterMaxTemp, 28);
    lv_obj_set_x(ui_HeaterMaxTemp, -6);
    lv_obj_set_y(ui_HeaterMaxTemp, 65);
    lv_obj_set_style_radius(ui_HeaterMaxTemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_HeaterMaxTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_HeaterMaxTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_outline_color(ui_HeaterMaxTemp, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_HeaterMaxTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_HeaterMaxTemp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_HeaterMaxTemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_HeaterMaxTemp, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeaterMaxTemp, lv_color_hex(0x00A0FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeaterMaxTemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_HeaterMaxTemp, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_HeaterMaxTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TextHeaterMaxTemp = lv_label_create(ui_HeaterMaxTemp);
    lv_obj_set_width(ui_TextHeaterMaxTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextHeaterMaxTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextHeaterMaxTemp, -4);
    lv_obj_set_y(ui_TextHeaterMaxTemp, 0);
    lv_obj_set_align(ui_TextHeaterMaxTemp, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextHeaterMaxTemp, "200℃");
    ui_object_set_themeable_style_property(ui_TextHeaterMaxTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextHeaterMaxTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextHeaterMaxTemp, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameHeaterMaxTemp = lv_label_create(ui_HeaterMaxTemp);
    lv_obj_set_width(ui_NameHeaterMaxTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameHeaterMaxTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameHeaterMaxTemp, 4);
    lv_obj_set_y(ui_NameHeaterMaxTemp, 0);
    lv_obj_set_align(ui_NameHeaterMaxTemp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NameHeaterMaxTemp, "加热台 - 最高温度");
    lv_obj_set_style_text_color(ui_NameHeaterMaxTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NameHeaterMaxTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NameHeaterMaxTemp, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeatingTime = lv_slider_create(ui_SystemSetting);
    lv_slider_set_range(ui_HeatingTime, 0, 60);
    lv_slider_set_value(ui_HeatingTime, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_HeatingTime) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_HeatingTime, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_HeatingTime, 268);
    lv_obj_set_height(ui_HeatingTime, 28);
    lv_obj_set_x(ui_HeatingTime, -6);
    lv_obj_set_y(ui_HeatingTime, 101);
    lv_obj_set_style_radius(ui_HeatingTime, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_HeatingTime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_HeatingTime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_outline_color(ui_HeatingTime, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_HeatingTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_HeatingTime, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_HeatingTime, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_HeatingTime, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeatingTime, lv_color_hex(0x0032FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeatingTime, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_HeatingTime, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_HeatingTime, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TextHeatingTime = lv_label_create(ui_HeatingTime);
    lv_obj_set_width(ui_TextHeatingTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextHeatingTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextHeatingTime, -4);
    lv_obj_set_y(ui_TextHeatingTime, 0);
    lv_obj_set_align(ui_TextHeatingTime, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextHeatingTime, "0Min");
    ui_object_set_themeable_style_property(ui_TextHeatingTime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextHeatingTime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextHeatingTime, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameHeatingTime = lv_label_create(ui_HeatingTime);
    lv_obj_set_width(ui_NameHeatingTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameHeatingTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameHeatingTime, 4);
    lv_obj_set_y(ui_NameHeatingTime, 0);
    lv_obj_set_align(ui_NameHeatingTime, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NameHeatingTime, "加热台 - 加热时间");
    lv_obj_set_style_text_color(ui_NameHeatingTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NameHeatingTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NameHeatingTime, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SystemBrightness = lv_slider_create(ui_SystemSetting);
    lv_slider_set_range(ui_SystemBrightness, 10, 100);
    lv_slider_set_value(ui_SystemBrightness, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SystemBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SystemBrightness, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_SystemBrightness, 268);
    lv_obj_set_height(ui_SystemBrightness, 28);
    lv_obj_set_x(ui_SystemBrightness, -6);
    lv_obj_set_y(ui_SystemBrightness, 137);
    lv_obj_set_style_radius(ui_SystemBrightness, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SystemBrightness, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_SystemBrightness, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_outline_color(ui_SystemBrightness, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SystemBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SystemBrightness, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SystemBrightness, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SystemBrightness, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SystemBrightness, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Container);
    ui_object_set_themeable_style_property(ui_SystemBrightness, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Container);

    lv_obj_set_style_blend_mode(ui_SystemBrightness, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_SystemBrightness, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ImageBrightness = lv_img_create(ui_SystemBrightness);
    lv_img_set_src(ui_ImageBrightness, &ui_img_637286161);
    lv_obj_set_width(ui_ImageBrightness, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageBrightness, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageBrightness, 13);
    lv_obj_set_y(ui_ImageBrightness, 0);
    lv_obj_set_align(ui_ImageBrightness, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageBrightness, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextBrightness = lv_label_create(ui_SystemBrightness);
    lv_obj_set_width(ui_TextBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextBrightness, -10);
    lv_obj_set_y(ui_TextBrightness, 0);
    lv_obj_set_align(ui_TextBrightness, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextBrightness, "50%");
    ui_object_set_themeable_style_property(ui_TextBrightness, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextBrightness, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextBrightness, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingSave = lv_btn_create(ui_SystemSetting);
    lv_obj_set_width(ui_SettingSave, 272);
    lv_obj_set_height(ui_SettingSave, 24);
    lv_obj_set_x(ui_SettingSave, -8);
    lv_obj_set_y(ui_SettingSave, 171);
    lv_obj_add_flag(ui_SettingSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingSave, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingSave, lv_color_hex(0x00FF8C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingSave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SettingSave, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SettingSave, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextSetting = lv_label_create(ui_SettingSave);
    lv_obj_set_width(ui_TextSetting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextSetting, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextSetting, "保存设置");
    lv_obj_set_style_text_font(ui_TextSetting, &ui_font_ASCII19, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SystemSettingBack, ui_event_SystemSettingBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PIDSetting, ui_event_PIDSetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ReflowSetting, ui_event_ReflowSetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HeaterMaxTemp, ui_event_HeaterMaxTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HeatingTime, ui_event_HeatingTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SystemBrightness, ui_event_SystemBrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingSave, ui_event_SettingSave, LV_EVENT_ALL, NULL);

}

void ui_SystemSettingScreen_screen_destroy(void)
{
    if(ui_SystemSettingScreen) lv_obj_del(ui_SystemSettingScreen);

    // NULL screen variables
    ui_SystemSettingScreen = NULL;
    ui_SystemSettingDock = NULL;
    ui_TextSystemSetting = NULL;
    ui_SystemSettingBack = NULL;
    ui_SystemSetting = NULL;
    ui_PIDSetting = NULL;
    ui_TextPIDSetting = NULL;
    ui_ReflowSetting = NULL;
    ui_TextReflowSetting = NULL;
    ui_HeaterMaxTemp = NULL;
    ui_TextHeaterMaxTemp = NULL;
    ui_NameHeaterMaxTemp = NULL;
    ui_HeatingTime = NULL;
    ui_TextHeatingTime = NULL;
    ui_NameHeatingTime = NULL;
    ui_SystemBrightness = NULL;
    ui_ImageBrightness = NULL;
    ui_TextBrightness = NULL;
    ui_SettingSave = NULL;
    ui_TextSetting = NULL;

}
