// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI

#include "../ui.h"

lv_obj_t * ui_UserSettingScreen = NULL;
lv_obj_t * ui_UserSettingHeader = NULL;
lv_obj_t * ui_TextUserSettingHeader = NULL;
lv_obj_t * ui_UserSettingBack = NULL;
lv_obj_t * ui_UserSettingDock = NULL;
lv_obj_t * ui_UserChart = NULL;
lv_obj_t * ui_Temp1 = NULL;
lv_obj_t * ui_TextTemp1 = NULL;
lv_obj_t * ui_NameTemp1 = NULL;
lv_obj_t * ui_Temp2 = NULL;
lv_obj_t * ui_TextTemp2 = NULL;
lv_obj_t * ui_NameTemp2 = NULL;
lv_obj_t * ui_Temp3 = NULL;
lv_obj_t * ui_TextTemp3 = NULL;
lv_obj_t * ui_NameTemp3 = NULL;
lv_obj_t * ui_Temp4 = NULL;
lv_obj_t * ui_TextTemp4 = NULL;
lv_obj_t * ui_NameTemp4 = NULL;
lv_obj_t * ui_Temp5 = NULL;
lv_obj_t * ui_TextTemp5 = NULL;
lv_obj_t * ui_NameTemp5 = NULL;
lv_obj_t * ui_Time1 = NULL;
lv_obj_t * ui_TextTime1 = NULL;
lv_obj_t * ui_NameTime1 = NULL;
lv_obj_t * ui_Time2 = NULL;
lv_obj_t * ui_TextTime2 = NULL;
lv_obj_t * ui_NameTime2 = NULL;
lv_obj_t * ui_Time3 = NULL;
lv_obj_t * ui_TextTime3 = NULL;
lv_obj_t * ui_NameTime3 = NULL;
lv_obj_t * ui_Time4 = NULL;
lv_obj_t * ui_TextTime4 = NULL;
lv_obj_t * ui_NameTime4 = NULL;
lv_obj_t * ui_Time5 = NULL;
lv_obj_t * ui_TextTime5 = NULL;
lv_obj_t * ui_NameTime5 = NULL;
// event funtions

// build funtions

void ui_UserSettingScreen_screen_init(void)
{
    ui_UserSettingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_UserSettingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UserSettingScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserSettingScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserSettingHeader = lv_obj_create(ui_UserSettingScreen);
    lv_obj_remove_style_all(ui_UserSettingHeader);
    lv_obj_set_width(ui_UserSettingHeader, 316);
    lv_obj_set_height(ui_UserSettingHeader, 20);
    lv_obj_set_x(ui_UserSettingHeader, 0);
    lv_obj_set_y(ui_UserSettingHeader, 2);
    lv_obj_set_align(ui_UserSettingHeader, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_UserSettingHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_UserSettingHeader, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UserSettingHeader, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserSettingHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextUserSettingHeader = lv_label_create(ui_UserSettingHeader);
    lv_obj_set_width(ui_TextUserSettingHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextUserSettingHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextUserSettingHeader, 0);
    lv_obj_set_y(ui_TextUserSettingHeader, -1);
    lv_obj_set_align(ui_TextUserSettingHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextUserSettingHeader, "自定曲线设置");
    ui_object_set_themeable_style_property(ui_TextUserSettingHeader, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextUserSettingHeader, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextUserSettingHeader, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserSettingBack = lv_btn_create(ui_UserSettingScreen);
    lv_obj_set_width(ui_UserSettingBack, 32);
    lv_obj_set_height(ui_UserSettingBack, 212);
    lv_obj_set_x(ui_UserSettingBack, -286);
    lv_obj_set_y(ui_UserSettingBack, 25);
    lv_obj_set_align(ui_UserSettingBack, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_UserSettingBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_UserSettingBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_UserSettingBack, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UserSettingBack, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserSettingBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_UserSettingBack, &ui_img_852573520, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_UserSettingBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_UserSettingBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserSettingDock = lv_obj_create(ui_UserSettingScreen);
    lv_obj_set_width(ui_UserSettingDock, 281);
    lv_obj_set_height(ui_UserSettingDock, 212);
    lv_obj_set_x(ui_UserSettingDock, 36);
    lv_obj_set_y(ui_UserSettingDock, 25);
    lv_obj_clear_flag(ui_UserSettingDock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_UserSettingDock, LV_DIR_VER);
    lv_obj_set_style_radius(ui_UserSettingDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UserSettingDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserSettingDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_UserSettingDock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_UserSettingDock, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserSettingDock, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_UserChart = lv_chart_create(ui_UserSettingDock);
    lv_obj_set_width(ui_UserChart, 256);
    lv_obj_set_height(ui_UserChart, 74);
    lv_obj_set_x(ui_UserChart, 10);
    lv_obj_set_y(ui_UserChart, -10);
    lv_obj_set_align(ui_UserChart, LV_ALIGN_TOP_MID);
    lv_chart_set_type(ui_UserChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_UserChart, 350);
    lv_chart_set_range(ui_UserChart, LV_CHART_AXIS_PRIMARY_Y, 0, 400);
    lv_chart_set_range(ui_UserChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_UserChart, 5, 0);
    lv_chart_set_axis_tick(ui_UserChart, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_UserChart, LV_CHART_AXIS_PRIMARY_Y, 1, 0, 5, 1, true, 0);
    lv_chart_set_axis_tick(ui_UserChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    lv_obj_set_style_radius(ui_UserChart, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_UserChart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_UserChart, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_UserChart, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_UserChart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_UserChart, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UserChart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UserChart, &ui_font_Chart, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Temp1 = lv_slider_create(ui_UserSettingDock);
    lv_slider_set_range(ui_Temp1, 100, 350);
    lv_slider_set_value(ui_Temp1, 200, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Temp1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Temp1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Temp1, 130);
    lv_obj_set_height(ui_Temp1, 20);
    lv_obj_set_x(ui_Temp1, -8);
    lv_obj_set_y(ui_Temp1, 70);
    lv_obj_set_style_radius(ui_Temp1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Temp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Temp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_outline_color(ui_Temp1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Temp1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Temp1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Temp1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Temp1, lv_color_hex(0x00A0FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Temp1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_Temp1, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Temp1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TextTemp1 = lv_label_create(ui_Temp1);
    lv_obj_set_width(ui_TextTemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextTemp1, -4);
    lv_obj_set_y(ui_TextTemp1, 0);
    lv_obj_set_align(ui_TextTemp1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextTemp1, "200℃");
    ui_object_set_themeable_style_property(ui_TextTemp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextTemp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextTemp1, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameTemp1 = lv_label_create(ui_Temp1);
    lv_obj_set_width(ui_NameTemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameTemp1, 4);
    lv_obj_set_y(ui_NameTemp1, 0);
    lv_obj_set_align(ui_NameTemp1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NameTemp1, "温度<1>");
    lv_obj_set_style_text_color(ui_NameTemp1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NameTemp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NameTemp1, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp2 = lv_slider_create(ui_UserSettingDock);
    lv_slider_set_range(ui_Temp2, 100, 350);
    lv_slider_set_value(ui_Temp2, 200, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Temp2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Temp2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Temp2, 130);
    lv_obj_set_height(ui_Temp2, 20);
    lv_obj_set_x(ui_Temp2, -8);
    lv_obj_set_y(ui_Temp2, 96);
    lv_obj_set_style_radius(ui_Temp2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Temp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Temp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_outline_color(ui_Temp2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Temp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Temp2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Temp2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Temp2, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Temp2, lv_color_hex(0x00A0FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Temp2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_Temp2, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Temp2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TextTemp2 = lv_label_create(ui_Temp2);
    lv_obj_set_width(ui_TextTemp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextTemp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextTemp2, -4);
    lv_obj_set_y(ui_TextTemp2, 0);
    lv_obj_set_align(ui_TextTemp2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextTemp2, "200℃");
    ui_object_set_themeable_style_property(ui_TextTemp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextTemp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextTemp2, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameTemp2 = lv_label_create(ui_Temp2);
    lv_obj_set_width(ui_NameTemp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameTemp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameTemp2, 4);
    lv_obj_set_y(ui_NameTemp2, 0);
    lv_obj_set_align(ui_NameTemp2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NameTemp2, "温度<2>");
    lv_obj_set_style_text_color(ui_NameTemp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NameTemp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NameTemp2, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp3 = lv_slider_create(ui_UserSettingDock);
    lv_slider_set_range(ui_Temp3, 100, 350);
    lv_slider_set_value(ui_Temp3, 200, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Temp3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Temp3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Temp3, 130);
    lv_obj_set_height(ui_Temp3, 20);
    lv_obj_set_x(ui_Temp3, -8);
    lv_obj_set_y(ui_Temp3, 122);
    lv_obj_set_style_radius(ui_Temp3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Temp3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Temp3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_outline_color(ui_Temp3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Temp3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Temp3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Temp3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Temp3, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Temp3, lv_color_hex(0x00A0FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Temp3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_Temp3, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Temp3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TextTemp3 = lv_label_create(ui_Temp3);
    lv_obj_set_width(ui_TextTemp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextTemp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextTemp3, -4);
    lv_obj_set_y(ui_TextTemp3, 0);
    lv_obj_set_align(ui_TextTemp3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextTemp3, "200℃");
    ui_object_set_themeable_style_property(ui_TextTemp3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextTemp3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextTemp3, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameTemp3 = lv_label_create(ui_Temp3);
    lv_obj_set_width(ui_NameTemp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameTemp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameTemp3, 4);
    lv_obj_set_y(ui_NameTemp3, 0);
    lv_obj_set_align(ui_NameTemp3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NameTemp3, "温度<3>");
    lv_obj_set_style_text_color(ui_NameTemp3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NameTemp3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NameTemp3, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp4 = lv_slider_create(ui_UserSettingDock);
    lv_slider_set_range(ui_Temp4, 100, 350);
    lv_slider_set_value(ui_Temp4, 200, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Temp4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Temp4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Temp4, 130);
    lv_obj_set_height(ui_Temp4, 20);
    lv_obj_set_x(ui_Temp4, -8);
    lv_obj_set_y(ui_Temp4, 148);
    lv_obj_set_style_radius(ui_Temp4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Temp4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Temp4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_outline_color(ui_Temp4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Temp4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Temp4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Temp4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Temp4, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Temp4, lv_color_hex(0x00A0FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Temp4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_Temp4, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Temp4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TextTemp4 = lv_label_create(ui_Temp4);
    lv_obj_set_width(ui_TextTemp4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextTemp4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextTemp4, -4);
    lv_obj_set_y(ui_TextTemp4, 0);
    lv_obj_set_align(ui_TextTemp4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextTemp4, "200℃");
    ui_object_set_themeable_style_property(ui_TextTemp4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextTemp4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextTemp4, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameTemp4 = lv_label_create(ui_Temp4);
    lv_obj_set_width(ui_NameTemp4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameTemp4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameTemp4, 4);
    lv_obj_set_y(ui_NameTemp4, 0);
    lv_obj_set_align(ui_NameTemp4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NameTemp4, "温度<4>");
    lv_obj_set_style_text_color(ui_NameTemp4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NameTemp4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NameTemp4, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp5 = lv_slider_create(ui_UserSettingDock);
    lv_slider_set_range(ui_Temp5, 100, 350);
    lv_slider_set_value(ui_Temp5, 200, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Temp5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Temp5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Temp5, 130);
    lv_obj_set_height(ui_Temp5, 20);
    lv_obj_set_x(ui_Temp5, -8);
    lv_obj_set_y(ui_Temp5, 174);
    lv_obj_set_style_radius(ui_Temp5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Temp5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Temp5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_outline_color(ui_Temp5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Temp5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Temp5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Temp5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Temp5, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Temp5, lv_color_hex(0x00A0FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Temp5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_Temp5, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Temp5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TextTemp5 = lv_label_create(ui_Temp5);
    lv_obj_set_width(ui_TextTemp5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextTemp5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextTemp5, -4);
    lv_obj_set_y(ui_TextTemp5, 0);
    lv_obj_set_align(ui_TextTemp5, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextTemp5, "200℃");
    ui_object_set_themeable_style_property(ui_TextTemp5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextTemp5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextTemp5, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameTemp5 = lv_label_create(ui_Temp5);
    lv_obj_set_width(ui_NameTemp5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameTemp5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameTemp5, 4);
    lv_obj_set_y(ui_NameTemp5, 0);
    lv_obj_set_align(ui_NameTemp5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NameTemp5, "温度<5>");
    lv_obj_set_style_text_color(ui_NameTemp5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NameTemp5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NameTemp5, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time1 = lv_slider_create(ui_UserSettingDock);
    lv_slider_set_range(ui_Time1, 0, 300);
    lv_slider_set_value(ui_Time1, 180, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Time1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Time1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Time1, 130);
    lv_obj_set_height(ui_Time1, 20);
    lv_obj_set_x(ui_Time1, 133);
    lv_obj_set_y(ui_Time1, 70);
    lv_obj_set_style_radius(ui_Time1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Time1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Time1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_outline_color(ui_Time1, lv_color_hex(0x00FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Time1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Time1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Time1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Time1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Time1, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Time1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_Time1, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Time1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TextTime1 = lv_label_create(ui_Time1);
    lv_obj_set_width(ui_TextTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextTime1, -4);
    lv_obj_set_y(ui_TextTime1, 0);
    lv_obj_set_align(ui_TextTime1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextTime1, "180S");
    ui_object_set_themeable_style_property(ui_TextTime1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextTime1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextTime1, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameTime1 = lv_label_create(ui_Time1);
    lv_obj_set_width(ui_NameTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameTime1, 4);
    lv_obj_set_y(ui_NameTime1, 0);
    lv_obj_set_align(ui_NameTime1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NameTime1, "时间<1>");
    lv_obj_set_style_text_color(ui_NameTime1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NameTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NameTime1, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time2 = lv_slider_create(ui_UserSettingDock);
    lv_slider_set_range(ui_Time2, 0, 300);
    lv_slider_set_value(ui_Time2, 180, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Time2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Time2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Time2, 130);
    lv_obj_set_height(ui_Time2, 20);
    lv_obj_set_x(ui_Time2, 133);
    lv_obj_set_y(ui_Time2, 96);
    lv_obj_set_style_radius(ui_Time2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Time2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Time2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_outline_color(ui_Time2, lv_color_hex(0x00FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Time2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Time2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Time2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Time2, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Time2, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Time2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_Time2, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Time2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TextTime2 = lv_label_create(ui_Time2);
    lv_obj_set_width(ui_TextTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextTime2, -4);
    lv_obj_set_y(ui_TextTime2, 0);
    lv_obj_set_align(ui_TextTime2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextTime2, "180S");
    ui_object_set_themeable_style_property(ui_TextTime2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextTime2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextTime2, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameTime2 = lv_label_create(ui_Time2);
    lv_obj_set_width(ui_NameTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameTime2, 4);
    lv_obj_set_y(ui_NameTime2, 0);
    lv_obj_set_align(ui_NameTime2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NameTime2, "时间<2>");
    lv_obj_set_style_text_color(ui_NameTime2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NameTime2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NameTime2, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time3 = lv_slider_create(ui_UserSettingDock);
    lv_slider_set_range(ui_Time3, 0, 300);
    lv_slider_set_value(ui_Time3, 180, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Time3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Time3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Time3, 130);
    lv_obj_set_height(ui_Time3, 20);
    lv_obj_set_x(ui_Time3, 133);
    lv_obj_set_y(ui_Time3, 122);
    lv_obj_set_style_radius(ui_Time3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Time3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Time3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_outline_color(ui_Time3, lv_color_hex(0x00FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Time3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Time3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Time3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Time3, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Time3, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Time3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_Time3, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Time3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TextTime3 = lv_label_create(ui_Time3);
    lv_obj_set_width(ui_TextTime3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextTime3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextTime3, -4);
    lv_obj_set_y(ui_TextTime3, 0);
    lv_obj_set_align(ui_TextTime3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextTime3, "180S");
    ui_object_set_themeable_style_property(ui_TextTime3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextTime3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextTime3, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameTime3 = lv_label_create(ui_Time3);
    lv_obj_set_width(ui_NameTime3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameTime3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameTime3, 4);
    lv_obj_set_y(ui_NameTime3, 0);
    lv_obj_set_align(ui_NameTime3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NameTime3, "时间<3>");
    lv_obj_set_style_text_color(ui_NameTime3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NameTime3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NameTime3, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time4 = lv_slider_create(ui_UserSettingDock);
    lv_slider_set_range(ui_Time4, 0, 300);
    lv_slider_set_value(ui_Time4, 180, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Time4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Time4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Time4, 130);
    lv_obj_set_height(ui_Time4, 20);
    lv_obj_set_x(ui_Time4, 133);
    lv_obj_set_y(ui_Time4, 148);
    lv_obj_set_style_radius(ui_Time4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Time4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Time4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_outline_color(ui_Time4, lv_color_hex(0x00FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Time4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Time4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Time4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Time4, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Time4, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Time4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_Time4, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Time4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TextTime4 = lv_label_create(ui_Time4);
    lv_obj_set_width(ui_TextTime4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextTime4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextTime4, -4);
    lv_obj_set_y(ui_TextTime4, 0);
    lv_obj_set_align(ui_TextTime4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextTime4, "180S");
    ui_object_set_themeable_style_property(ui_TextTime4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextTime4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextTime4, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameTime4 = lv_label_create(ui_Time4);
    lv_obj_set_width(ui_NameTime4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameTime4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameTime4, 4);
    lv_obj_set_y(ui_NameTime4, 0);
    lv_obj_set_align(ui_NameTime4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NameTime4, "时间<4>");
    lv_obj_set_style_text_color(ui_NameTime4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NameTime4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NameTime4, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time5 = lv_slider_create(ui_UserSettingDock);
    lv_slider_set_range(ui_Time5, 0, 300);
    lv_slider_set_value(ui_Time5, 180, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Time5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Time5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Time5, 130);
    lv_obj_set_height(ui_Time5, 20);
    lv_obj_set_x(ui_Time5, 133);
    lv_obj_set_y(ui_Time5, 174);
    lv_obj_set_style_radius(ui_Time5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Time5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_ButtonAndBack);
    ui_object_set_themeable_style_property(ui_Time5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_ButtonAndBack);
    lv_obj_set_style_outline_color(ui_Time5, lv_color_hex(0x00FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Time5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Time5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Time5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Time5, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Time5, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Time5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_Time5, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Time5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TextTime5 = lv_label_create(ui_Time5);
    lv_obj_set_width(ui_TextTime5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextTime5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextTime5, -4);
    lv_obj_set_y(ui_TextTime5, 0);
    lv_obj_set_align(ui_TextTime5, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextTime5, "180S");
    ui_object_set_themeable_style_property(ui_TextTime5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextAndImage);
    ui_object_set_themeable_style_property(ui_TextTime5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextAndImage);
    lv_obj_set_style_text_font(ui_TextTime5, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameTime5 = lv_label_create(ui_Time5);
    lv_obj_set_width(ui_NameTime5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameTime5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameTime5, 4);
    lv_obj_set_y(ui_NameTime5, 0);
    lv_obj_set_align(ui_NameTime5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NameTime5, "时间<5>");
    lv_obj_set_style_text_color(ui_NameTime5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NameTime5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NameTime5, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_UserSettingBack, ui_event_UserSettingBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Temp1, ui_event_Temp1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Temp2, ui_event_Temp2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Temp3, ui_event_Temp3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Temp4, ui_event_Temp4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Temp5, ui_event_Temp5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Time1, ui_event_Time1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Time2, ui_event_Time2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Time3, ui_event_Time3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Time4, ui_event_Time4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Time5, ui_event_Time5, LV_EVENT_ALL, NULL);

}

void ui_UserSettingScreen_screen_destroy(void)
{
    if(ui_UserSettingScreen) lv_obj_del(ui_UserSettingScreen);

    // NULL screen variables
    ui_UserSettingScreen = NULL;
    ui_UserSettingHeader = NULL;
    ui_TextUserSettingHeader = NULL;
    ui_UserSettingBack = NULL;
    ui_UserSettingDock = NULL;
    ui_UserChart = NULL;
    ui_Temp1 = NULL;
    ui_TextTemp1 = NULL;
    ui_NameTemp1 = NULL;
    ui_Temp2 = NULL;
    ui_TextTemp2 = NULL;
    ui_NameTemp2 = NULL;
    ui_Temp3 = NULL;
    ui_TextTemp3 = NULL;
    ui_NameTemp3 = NULL;
    ui_Temp4 = NULL;
    ui_TextTemp4 = NULL;
    ui_NameTemp4 = NULL;
    ui_Temp5 = NULL;
    ui_TextTemp5 = NULL;
    ui_NameTemp5 = NULL;
    ui_Time1 = NULL;
    ui_TextTime1 = NULL;
    ui_NameTime1 = NULL;
    ui_Time2 = NULL;
    ui_TextTime2 = NULL;
    ui_NameTime2 = NULL;
    ui_Time3 = NULL;
    ui_TextTime3 = NULL;
    ui_NameTime3 = NULL;
    ui_Time4 = NULL;
    ui_TextTime4 = NULL;
    ui_NameTime4 = NULL;
    ui_Time5 = NULL;
    ui_TextTime5 = NULL;
    ui_NameTime5 = NULL;

}
