// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI

#ifndef UI_USERSETTINGSCREEN_H
#define UI_USERSETTINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_UserSettingScreen
extern void ui_UserSettingScreen_screen_init(void);
extern void ui_UserSettingScreen_screen_destroy(void);
extern lv_obj_t * ui_UserSettingScreen;
extern lv_obj_t * ui_UserSettingHeader;
extern lv_obj_t * ui_TextUserSettingHeader;
extern void ui_event_UserSettingBack(lv_event_t * e);
extern lv_obj_t * ui_UserSettingBack;
extern lv_obj_t * ui_UserSettingDock;
extern lv_obj_t * ui_UserChart;
extern void ui_event_Temp1(lv_event_t * e);
extern lv_obj_t * ui_Temp1;
extern lv_obj_t * ui_TextTemp1;
extern lv_obj_t * ui_NameTemp1;
extern void ui_event_Temp2(lv_event_t * e);
extern lv_obj_t * ui_Temp2;
extern lv_obj_t * ui_TextTemp2;
extern lv_obj_t * ui_NameTemp2;
extern void ui_event_Temp3(lv_event_t * e);
extern lv_obj_t * ui_Temp3;
extern lv_obj_t * ui_TextTemp3;
extern lv_obj_t * ui_NameTemp3;
extern void ui_event_Temp4(lv_event_t * e);
extern lv_obj_t * ui_Temp4;
extern lv_obj_t * ui_TextTemp4;
extern lv_obj_t * ui_NameTemp4;
extern void ui_event_Temp5(lv_event_t * e);
extern lv_obj_t * ui_Temp5;
extern lv_obj_t * ui_TextTemp5;
extern lv_obj_t * ui_NameTemp5;
extern void ui_event_Time1(lv_event_t * e);
extern lv_obj_t * ui_Time1;
extern lv_obj_t * ui_TextTime1;
extern lv_obj_t * ui_NameTime1;
extern void ui_event_Time2(lv_event_t * e);
extern lv_obj_t * ui_Time2;
extern lv_obj_t * ui_TextTime2;
extern lv_obj_t * ui_NameTime2;
extern void ui_event_Time3(lv_event_t * e);
extern lv_obj_t * ui_Time3;
extern lv_obj_t * ui_TextTime3;
extern lv_obj_t * ui_NameTime3;
extern void ui_event_Time4(lv_event_t * e);
extern lv_obj_t * ui_Time4;
extern lv_obj_t * ui_TextTime4;
extern lv_obj_t * ui_NameTime4;
extern void ui_event_Time5(lv_event_t * e);
extern lv_obj_t * ui_Time5;
extern lv_obj_t * ui_TextTime5;
extern lv_obj_t * ui_NameTime5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

